package org.dragon.workspace.member;

import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Character Duty 实体
 * 存储每个 Character 在特定 workspace 下的职责描述
 *
 * @author wyj
 * @version 1.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CharacterDuty {

    /**
     * 创建复合 ID
     */
    public static String createId(String workspaceId, String characterId) {
        return workspaceId + "_" + characterId;
    }

    /**
     * 唯一标识 (workspaceId_characterId)
     */
    private String id;

    /**
     * Workspace ID
     */
    private String workspaceId;

    /**
     * Character ID
     */
    private String characterId;

    /**
     * 职责描述
     */
    private String dutyDescription;

    /**
     * 是否自动生成
     */
    @Builder.Default
    private boolean autoGenerated = false;

    /**
     * 创建时间
     */
    private LocalDateTime createdAt;

    /**
     * 更新时间
     */
    private LocalDateTime updatedAt;
}
